### ISSUE TITLE
Disable Always Displaying to Players

### ISSUE THREAD

**Issue by huanmeng-qwq** [unldenis/holoeasy#37]
Disable Always Displaying to Players
https://github.com/unldenis/Hologram-Lib/blob/5e64ed08b0e6f08e49aea08b3d5e42a3ca148411/src/main/java/com/github/unldenis/hologram/HologramPool.java#L115-L117

I hope to have the freedom to control whether to show to players

**Comment by huanmeng-qwq** [comment]
Also, there are still some issues with the current interactive judgment, which requires the perspective to be lowered to determine, rather than aiming the perspective at the text, and does not support right-click

**Comment by unldenis** [comment]
> I hope to have the freedom to control whether to show to players

If you want to manage these things yourself, maybe you should not use pools?

> Also, there are still some issues with the current interactive judgment, which requires the perspective to be lowered to determine, rather than aiming the perspective at the text

I did not understand well

> and does not support right-click

this can be added to the library
