### ISSUE TITLE
Changing the text of an holo that already haves text bugs it

### ISSUE THREAD

**Issue by Guarmanda** [unldenis/holoeasy#46]
Executing this code:
```Java
		TextLine textLine = new TextLine((Plugin)Main.getInstance(), name, null, false);
		hologram.load(textLine);
```
in 1.16.5 on a new hologram doesn't cause issue. Bug an hologram that already has text will bug. That being said, the hologram is correctly remove on logout/login.
I chose to remove the hologram before changing its text, and it works, so I won't have this bug in other versions (sorry)

**Comment by unldenis** [comment]
I didn't quite understand the problem.
