### ISSUE TITLE
Add info on how to build sources

### ISSUE THREAD

**Issue by Guarmanda** [unldenis/holoeasy#50]
When using ./gradle build, we get an api-3.1.1.jar somewhere, but this jar isn't usable in production (missing kotlin classes)
The project may include some info on how to build it?

**Comment by unldenis** [comment]
Brought back to Maven because I tried Gradle, but posting to a repository is not easy, not knowing it. However, if anyone is capable, I'm open to PR.

**Comment by GeorgeV220** [comment]
I did a little search and I managed to compile a kotlin project with gradle and get the jar with this:
```groovy
plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.5.21'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

application {
    mainClassName = 'com.georgev22.tests.Main'
}

tasks.jar {
    manifest {
        attributes(
            'Main-Class': 'com.georgev22.tests.Main'
        )
    }
    from sourceSets.main.output
}``
