### ISSUE TITLE
Still doesn't work in 1.8 to 1.8.8

### ISSUE THREAD

**Issue by Guarmanda** [unldenis/holoeasy#52]
server error:
![image](https://github.com/unldenis/holoeasy/assets/7463055/3d578315-3419-4a59-bdec-6351b12c61c1)
client error on connection: (so client can't connect)
![image](https://github.com/unldenis/holoeasy/assets/7463055/139827a4-5f19-48e6-a0cb-2fc312bb5c98)

**Comment by unldenis** [comment]
I have already tested for 1.8.8 and it works, using DSL. Item lines are not supported.

**Comment by Guarmanda** [comment]
I don't use items, I just spawn simple lines^^ whatever, I'll keep using your old API for the moment, in combination with your new one
