### ISSUE TITLE
API looks terrible

### ISSUE THREAD

**Issue by Rollczi** [unldenis/holoeasy#62]
The API breaks basic OOP concepts, it abuses the getInstance method just to make something look "cool" and "Kotlin-like" (and it has nothing to do with how it is done in Kotlin).

**Comment by unldenis** [comment]
Thank you for your feedback! I appreciate your concerns about OOP principles and the use of getInstance. I'll try to clarify the intent behind the API design and some of the decisions made.

First, the API is strongly inspired by [Javalin](https://javalin.io/) and is designed with ease of use in mind for both Java and Kotlin. The goal was to create a fluent and expressive way of defining holograms while ensuring that performance remains optimal.

Regarding your point on Kotlin-like design: the API wasn't created for only Kotlin users, but rather to provide a clean, fluent API that works well in both Java and Kotlin environments. Kotlin's syntax allows for concise expressions, but that doesn't mean the Java version is compromised or non-idiomatic. In fact, the structure is carefully designed to avoid reflection and runtime overhead, keeping everything performant.

It's interesting that you mention OOP adherence, especially given that your framework LiteCommands rely heavily on annotations and reflection, which arguably deviate more from pure OOP principles than this API does. In contrast, my API uses zero reflection, which avoids some of the typical runtime performance hits associated with it.

Ultimately, the design choices here prioritize practical usability and performance. If you have specific suggestions on how to better align with OOP while maintaining these goals, I’m more than happy to discuss them!

**Comment by Rollczi** [comment]
Hi, thank you for your thoughtful response!

I realize I may not have been entirely clear before. 
Just to clarify: The javalin is not an argument for me whether it is good or not, even though I appreciate this project. 

In general, relying on methods that directly manipulate an object’s state can be seen as bad practice. There’s a good discussion on this topic [here](https://stackoverflow.com/questions/4002201/why-arent-static-methods-considered-good-oo-practice). I personally prefer using lambdas with parameters. (just like the rest of the [javalin API](https://javalin.io/documentation#before-handlers)). I’m not suggesting that annotations or reflection should be used in your case, because it doesn't make sense.

I understand that this ultimately comes down to preference, so I’ll leave it at that.

---

Regarding LiteCommands, I’m not sure how it connects to your library (?). But since it came up:

I can honestly say that reflection is used in around 90% while initializing, and the `invoke` method itself is not as costly as the overall validation, parsing, and feature handling processes.

LiteCommands also provides a [programmatic API](https://github.com/Rollczi/LiteCommands/blob/master/examples/bukkit/src/main/java/dev/rollczi/example/bukkit/ExamplePlugin.java#L73) that doesn’t rely on annotations.

Using reflection doesn’t necessarily break key OOP principles. Take Gson as an example – it’s widely used, (funnily [Javalin uses](https://github.com/javalin/javalin/tree/master/javalin/src/main/java/io/javalin/json) Gson). While manual JSON mapping is possible, but is there any point in doing so? It often introduces unnecessary complexity. If you still believe that this clearly violates OOP principles, then that's your perspective.

Annotations and dependency injection (DI) are always debated topics in best practices. It's generally wise to avoid tight coupling with frameworks or libraries. I don't need to debate or argue the use of tools like Spring and others. And I know it has its downsides.

**However, that’s not the main point of this discussion.**

**Comment by unldenis** [comment]
Hi @Rollczi , I understand what you're saying, and I accept it, although I don't fully agree.

I didn't particularly appreciate the title of the issue, "API looks terrible," as it's subjective. If you had suggestions or opened a PR with improvements, it would have made more sense. For example, I didn't say that LiteCommands API looks terrible just because I don't like annotations(not true).

This library has evolved from a standard OOP programming style to one inspired by the philosophy of [Composition over Inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance#:~:text=Composition%20over%20inheritance%20(or%20composite,from%20a%20base%20or%20parent) (versions < 3.0.0).

 As you can see, it hasn't remained the same over time, which shows that I'm open to improvements. Every API has its trade-offs: some are verbose but simple, others more complex but customizable, and so on.

**Comment by Rollczi** [comment]
Hi @unldenis 

I’m sorry about the title of the issue, I understand that it came off more harshly than intended. I respect the work you've put into this. 

I appreciate that you've been open to change, and I think it’s worth reconsidering your approach to creating an API. I believe there's value in rethinking how the current design balances complexity and usability.
