### ISSUE TITLE
The API is very fussy

### ISSUE THREAD

**Issue by vLuckyyy** [unldenis/holoeasy#63]
I currently have a problem with HoloEasy that makes working with holograms difficult. It lacks the ability to retrieve a hologram object in another context without knowing the UUID, which is not very practical. Often, when creating a hologram, I need to return to it later to edit or delete it in its entirety, for example. Introducing a method to search for a hologram by name or other properties that are easier to track than the UUID would make the job much easier. It would also be useful to have a function that returns a list of all holograms, which would make it possible to manage them dynamically without having to store the UUID in every part of the code

**Comment by unldenis** [comment]
I don't understand what problem you are trying to solve, if you can go into more detail maybe I can help you. 

When you create a hologram you can have its [reference](https://github.com/unldenis/holoeasy?tab=readme-ov-file#reactive-holograms). 

You also have access to its UUID.

**Comment by vLuckyyy** [comment]
In short I have a question, for what reason the hologram key was removed? it seemed to me that this is a good approach

But leaving aside this fact, I think it would be nice to add the ability to retrieve all the holograms, the usual method `getHolograms` would be quite enough, however, it would be nice if the named holograms came back, it may be an optional approach but it would still make the work easier, currently when I need to edit a hologram I have to store its uuid in another place to refer to it later, I do not want to be unkind but currently the API is very fussy and has few options....

**Comment by unldenis** [comment]
From version 4.0.0 it is possible to define custom data or other data in hologram classes, for example the name.
From 4.1.0 it is also possible to define Pools with custom hologram types.
Documentation is ongoing in this major version, more can be found in the examples.
