### ISSUE TITLE
Uue schematic versioning for future releases.

### ISSUE THREAD

**Issue by vLuckyyy** [unldenis/holoeasy#64]
In recent versions there were a lot of changes that breaks the compatibility of previous versions, it would be nice if HoloEasy used Schematic Versioning rules for future releases. this issue is just for information.

![image](https://github.com/user-attachments/assets/b3a11f0e-2fa6-431a-8fcc-960abc413e96)

**Comment by unldenis** [comment]
I'll be more strict with versioning!
